"use client";
import Image from "next/image";
import {FormEvent,useEffect,useMemo,useState} from "react";
const X_URL="https://x.com/ifagrithm?s=11", LINKEDIN_URL="https://www.linkedin.com/company/ifagrithm/", EMAIL="Ifagrithm@gmail.com";
const questions=["Who are our most valuable users and what else do they do?","Why are users leaving after an incentive?","Which market should we enter?","Is this partnership or integration worth pursuing?","Who actually reaches the audience we need?","Which distribution route produced valuable users?","Why aren't our sponsorship attempts converting?","What changed after we launched this intervention?"];
const services=[["Behaviour Intelligence","Understand relevant users, wallets, journeys, activity and behavioural patterns."],["Market & Competitor Intelligence","Investigate markets, alternatives, competitors and changing activity."],["Growth & Distribution Intelligence","Investigate where relevant audiences or behaviours already exist and practical routes to reach them."],["Decision Research & Advisory","Compare evidence, economics, risks and dependencies around a specific business decision."],["Measurement & Decision Learning","Investigate what happened after an intervention and what should be learned."],["Custom Data & Research","Datasets, analytics, data modelling, research infrastructure and defined analytical projects where required."]];
const onchain=["Transactions","Wallet activity","Protocol usage","Capital flows","Positions","Fees","Liquidity","Cross-protocol journeys","Retention / activity"], offchain=["Market research","Competitor activity","Social behaviour","Content engagement","Communities","Partnerships","Sponsorships","Distribution","Qualitative evidence"];
function Brand(){return <a className="brand" href="#top"><span className="logoWrap"><Image src="/ifagrithm-logo.png" alt="" width={40} height={40} priority/></span><span>IFAGRITHM</span></a>}
function Evidence({title,items}:{title:string,items:string[]}){return <div className="evidenceBox"><p className="miniLabel">{title}</p><div className="tagList">{items.map(x=><span key={x}>{x}</span>)}</div></div>}
export default function Site(){
 const [theme,setTheme]=useState<"dark"|"light">("dark"),[menu,setMenu]=useState(false),[status,setStatus]=useState("");
 const [brief,setBrief]=useState({name:"",company:"",email:"",question:"",decision:"",notes:""});
 useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
 const mailBody=useMemo(()=>encodeURIComponent(`Name: ${brief.name}\nCompany: ${brief.company}\nWork email: ${brief.email}\n\nBusiness question:\n${brief.question}\n\nDecision:\n${brief.decision}\n\nAdditional context:\n${brief.notes}`),[brief]);
 function submit(e:FormEvent){e.preventDefault();if(!brief.name.trim()||!brief.email.trim()||!brief.question.trim()||!brief.decision.trim()){setStatus("Please complete the required fields.");return}setStatus("Your email app will open with the project brief prepared. Nothing is stored on this website.");window.location.href=`mailto:${EMAIL}?subject=${encodeURIComponent("IFAGRITHM project question — "+brief.company)}&body=${mailBody}`}
 async function copyBrief(){const t=`IFAGRITHM PROJECT BRIEF\n\nName: ${brief.name}\nCompany: ${brief.company}\nWork email: ${brief.email}\n\nBusiness question:\n${brief.question}\n\nDecision:\n${brief.decision}\n\nAdditional context:\n${brief.notes}`;try{await navigator.clipboard.writeText(t);setStatus("Project brief copied.")}catch{setStatus("Copy unavailable on this browser. You can email the brief instead.")}}
 return <><header className="nav" id="top"><div className="shell navInner"><Brand/><nav id="primary-navigation" aria-label="Main navigation" onClick={()=>setMenu(false)} className={menu?"navLinks open":"navLinks"}><a href="#research">Research</a><a href="#services">Services</a><a href="#method">Method</a><a href="#about">About</a><a className="navCta" href="#contact">Bring us a question</a></nav><div className="navActions"><button className="iconBtn" onClick={()=>setTheme(theme==="dark"?"light":"dark")} aria-label="Toggle theme">{theme==="dark"?"☀":"◐"}</button><button className="menuBtn" onClick={()=>setMenu(!menu)} aria-label="Toggle menu" aria-expanded={menu} aria-controls="primary-navigation">{menu?"×":"☰"}</button></div></div></header>
 <main>
 <section className="hero section"><div className="shell heroGrid"><div><p className="eyebrow">WEB3 DATA & RESEARCH</p><h1>We investigate the questions behind <em>business decisions.</em></h1><p className="lead">IFAGRITHM combines data, research and behavioural analysis to help Web3 teams understand what is happening, why it matters, and what may be worth doing next.</p><div className="actions"><a className="primary" href="#contact">Bring us a question <span>↗</span></a><a className="secondary" href="#research">Explore research</a></div></div><div className="systemCard"><p className="miniLabel">RESEARCH SYSTEM</p>{["Question","Evidence","Behaviour","Economic meaning","Decision"].map((x,i)=><div className="systemRow" key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong>{i<4&&<b>↓</b>}</div>)}<div className="systemFoot">The answer may be act, test, investigate further — or do nothing.</div></div></div></section>
 <section className="section ruled"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">EXAMPLE RESEARCH QUESTIONS</p><h2>Start with the question.</h2></div><p>Different business questions require different evidence. These are examples, not client claims.</p></div><div className="questionGrid">{questions.map((q,i)=><article className="questionCard" key={q}><span>0{i+1}</span><p>{q}</p><b>↗</b></article>)}</div></div></section>
 <section className="section evidence"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">EVIDENCE</p><h2>The question determines the data.</h2></div><p>We don&apos;t force every problem into an on-chain dataset. We use the evidence the question requires.</p></div><div className="evidenceGrid"><Evidence title="ON-CHAIN" items={onchain}/><div className="researchCore"><span>QUESTION</span><i>→</i><strong>IFAGRITHM<br/>RESEARCH</strong><i>→</i><span>DECISION</span></div><Evidence title="OFF-CHAIN" items={offchain}/></div></div></section>
 <section className="section ruled"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">PROCESS</p><h2>From question to decision.</h2></div><p>Research is useful when it reduces uncertainty without pretending uncertainty has disappeared.</p></div><div className="process">{["Business question","Evidence","Behaviour & patterns","Economic meaning","Decision options","Test","Learn"].map((x,i)=><div className="processItem" key={x}><span>0{i+1}</span><strong>{x}</strong>{i<6&&<b>→</b>}</div>)}</div></div></section>
 <section className="section" id="services"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">SERVICES</p><h2>What we investigate.</h2></div><p>A project can combine several capabilities. We scope the actual question rather than forcing every team through the same package.</p></div><div className="serviceGrid">{services.map(([t,d],i)=><article className="service" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="section method ruled" id="method"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">METHOD</p><h2>Desire creates behaviour.</h2></div><p>DBB is the thinking underneath the work, not something a client must learn before bringing us a question.</p></div><div className="dbb">{[["DESIRE","People are trying to accomplish something."],["BEHAVIOUR","Their actions create observable patterns."],["BUSINESS","Repeated behaviour may reveal where a product can provide useful value."]].map(([a,b],i)=><div className="dbbCard" key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></div>)}</div><div className="bpa"><span>BEFORE</span><b>→</b><strong>PRODUCT</strong><b>→</b><span>AFTER</span><p>One structure we use to investigate the activity surrounding a product.</p></div></div></section>
 <section className="section" id="research"><div className="shell"><div className="sectionHead"><div><p className="eyebrow">PUBLIC RESEARCH</p><h2>Research.</h2></div><p>We will publish the question, evidence, method, findings, limitations and business implications — not decorative dashboards without context.</p></div><div className="researchPlaceholder"><div><span className="status">RESEARCH 001 · COMING SOON</span><h3>Our first public investigation.</h3><p>No client case studies are being invented here. Verified public work will replace this placeholder as it is completed.</p></div><div className="formats"><span>Behaviour Maps</span><span>Decision Briefs</span><span>Behaviour Signals</span></div></div></div></section>
 <section className="section about ruled" id="about"><div className="shell aboutGrid"><div><p className="eyebrow">ABOUT</p><h2>Why IFAGRITHM?</h2><p className="aboutLead">IFAGRITHM combines “Ifá” and “algorithm”. The name is inspired by interpreting patterns to inform guidance, combined with systematic computation and research.</p><p>Our commercial work is evidence-based: documented data, explicit assumptions, reproducible methods where appropriate, and clear uncertainty. The brand does not claim spiritual authority or equate data science with divination.</p></div><aside className="founder"><p className="miniLabel">FOUNDER</p><h3>Olamilekan Alaga</h3><p>MSc Data Science<br/>University of Greenwich</p><hr/><p>Web3 research · On-chain analytics · Behavioural analysis · Data analysis</p></aside></div></section>
 <section className="section contact" id="contact"><div className="shell contactGrid"><div><p className="eyebrow">PROJECT BRIEF</p><h2>Bring us a question worth investigating.</h2><p className="lead small">Tell us the decision you&apos;re trying to make, what you already know, and where the uncertainty is.</p><div className="contactLinks"><a href={`mailto:${EMAIL}`}>{EMAIL}</a><a href={X_URL} target="_blank" rel="noreferrer">X / @ifagrithm ↗</a><a href={LINKEDIN_URL} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><form className="briefForm" onSubmit={submit}><label>Name *<input required autoComplete="name" value={brief.name} onChange={e=>setBrief({...brief,name:e.target.value})}/></label><label>Company<input autoComplete="organization" value={brief.company} onChange={e=>setBrief({...brief,company:e.target.value})}/></label><label>Work email *<input required autoComplete="email" type="email" value={brief.email} onChange={e=>setBrief({...brief,email:e.target.value})}/></label><label>Business question *<textarea required value={brief.question} onChange={e=>setBrief({...brief,question:e.target.value})}/></label><label>What decision are you trying to make? *<textarea required value={brief.decision} onChange={e=>setBrief({...brief,decision:e.target.value})}/></label><label>Anything else we should know?<textarea value={brief.notes} onChange={e=>setBrief({...brief,notes:e.target.value})}/></label><div className="formActions"><button className="primary" type="submit">Email project brief ↗</button><button className="secondary button" type="button" onClick={copyBrief}>Copy brief</button></div>{status&&<p className="formStatus" aria-live="polite">{status}</p>}<p className="privacy">No form backend is connected in v1. Nothing entered here is stored by this website.</p></form></div></section>
 </main><footer><div className="shell footerGrid"><div><Brand/><p>Web3 Data & Research<br/>From behaviour to decisions.</p></div><div><a href="#research">Research</a><a href="#services">Services</a><a href="#method">Method</a><a href="#about">About</a></div><div><a href={X_URL} target="_blank" rel="noreferrer">X ↗</a><a href={LINKEDIN_URL} target="_blank" rel="noreferrer">LinkedIn ↗</a><a href={`mailto:${EMAIL}`}>Email ↗</a></div><small>© {new Date().getFullYear()} IFAGRITHM</small></div></footer></>}
